version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: dexo_postgres
    restart: always
    env_file: .env
    ports: ["5432:5432"]
    networks:
      - dexo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dexo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:8.0
    container_name: dexo-mongodb
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: logging
    ports: ["27017:27017"]
    networks:
      - dexo_network

  auth:
    container_name: auth_service
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports: ["8080:${AUTH_PORT}"]
    env_file:
      - .env
      - apps/auth/.env
    environment:
      MONGO_URI: ${MONGO_URI}
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
    depends_on:
      postgres: { condition: service_healthy }
      mongodb: { condition: service_started }
    networks:
      - dexo_network
    restart: always

  transaction:
    container_name: transaction_service
    build:
      context: .
      dockerfile: apps/transactions/Dockerfile
    ports: ["8081:${TRANSACTION_PORT}"]
    env_file:
      - .env
      - apps/transactions/.env
    environment:
      MONGO_URI: ${MONGO_URI}
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
    depends_on:
      mongodb: { condition: service_started }
    networks:
      - dexo_network
    restart: always

networks:
  dexo_network:
    driver: bridge
